"""create billing table

Revision ID: 3d40203f9f31
Revises: c5472511ef35
Create Date: 2026-08-06 12:00:22.193969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d40203f9f31'
down_revision: Union[str, Sequence[str], None] = 'c5472511ef35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bill_number', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', 'REFUNDED', name='billingstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'INSURANCE', name='paymentmethod'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_bill_number'), 'billings', ['bill_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billings_bill_number'), table_name='billings')
    op.drop_table('billings')
    # ### end Alembic commands ###
